name: 0.0.$(Build.BuildId)

pool:
  vmImage: 'ubuntu-20.04'

variables:
- name: letsEncryptUrl
  value: https://acme-v02.api.letsencrypt.org/directory
- name: letsEncryptHostname
  value: acme-v02.api.letsencrypt.org
- name: AcmeContact
  value: tim@homevalet.co
- group: Cloudflare
- group: LetsEncryptStorageSAS

schedules:
- cron: '0 2 * * *' # Everyday at 2am (Okta upload runs at 3am)
  branches:
    include:
    - trunk

trigger: none
pr: none

stages:
- stage: dev
  jobs:
  - deployment: auth-oktaPreview
    displayName: auth.homevalet.dev
    environment: Preview - Okta
    variables:
    - group: LetsEncryptStorageSAS - Dev
    - name: CertificateNames
      value: auth.homevalet.dev
    - name: KeyVaultResourceId
      value: /subscriptions/fde10e22-fd9d-46b2-8198-b30540d5c76d/resourceGroups/hv-dev-ops/providers/Microsoft.KeyVault/vaults/hv-dev-001-kv-ops-01
    strategy:
      runOnce:
        deploy:
          steps:
          - template: acme-update-steps.yml
  - deployment: wildcard-dev
    displayName: homevalet.dev,*.homevalet.dev
    environment: Development - Platform
    variables:
    - group: LetsEncryptStorageSAS - Dev
    - name: CertificateNames
      value: homevalet.dev,*.homevalet.dev
    - name: KeyVaultResourceId
      value: /subscriptions/fde10e22-fd9d-46b2-8198-b30540d5c76d/resourceGroups/hv-dev-ops/providers/Microsoft.KeyVault/vaults/hv-dev-001-kv-ops-01
    strategy:
      runOnce:
        deploy:
          steps:
          - template: acme-update-steps.yml
- stage: prd
  jobs:
  - deployment: auth-prd
    displayName: auth.homevalet.co
    environment: Okta
    variables:
    - group: LetsEncryptStorageSAS - Prod
    - name: CertificateNames
      value: auth.homevalet.co
    - name: KeyVaultResourceId
      value: /subscriptions/5231ee57-0984-4eda-8e8e-81cae16a67a4/resourceGroups/hv-prd-ops/providers/Microsoft.KeyVault/vaults/hv-prd-001-kv-ops-01
    strategy:
      runOnce:
        deploy:
          steps:
          - template: acme-update-steps.yml
  - deployment: wildcard-prd
    displayName: homevalet.co,*.homevalet.co
    environment: Production - Platform
    variables:
    - group: LetsEncryptStorageSAS - Prod
    - name: CertificateNames
      value: homevalet.co,*.homevalet.co
    - name: KeyVaultResourceId
      value: /subscriptions/5231ee57-0984-4eda-8e8e-81cae16a67a4/resourceGroups/hv-prd-ops/providers/Microsoft.KeyVault/vaults/hv-prd-001-kv-ops-01
    strategy:
      runOnce:
        deploy:
          steps:
          - template: acme-update-steps.yml